services:
  - type: web
    name: fill-sign-send
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/server.py
    plan: free
    autoDeploy: false
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: POKE_API_KEY
        value: pk_SrRDm-Dpg6wiszN-XYKyBPT4GRK0cBh4WwaOCDC0PEM
      - key: DOCUSIGN_BASE_PATH
        value: https://demo.docusign.net
      - key: DOCUSIGN_ACCOUNT_ID
        value: 3c08c9cc-3c87-4a5e-9f59-8ee3670ba4f4
      - key: DOCUSIGN_INTEGRATION_KEY
        value: d5866028-eab7-4a93-a595-130664eaac6b
      - key: DOCUSIGN_USER_ID
        value: 55269937-f820-4015-8f1f-415ce75b03f9
      - key: DOCUSIGN_PRIVATE_KEY
        value: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEoAIBAAKCAQEAgUTugzqt3Urm/xh5vfp/Y7CeXRgShcpEE/c4MgxdEjypOhqB
          XetqaFxwLJrzg7ZAqjiROdGN0/fbHudQtgjDjXI6gnAdQE6qzvRP/6MHoD5csooK
          0c0KSh4dTmAuFpFXxy6SHKSz6eA03ZGtbC2ufs/sRtA5dxQfsudOqMk0plKotugp
          nx6UsiH4SyNFytfYG8wiZW559+YFVybb0BFILheXE9aw2QTKWDmzS7xiETKA7NJ2
          eeYEINjzKDQNxIa3/IpMwRFySjmzRGvKN/PHsQuH+1D+D+lKCXp0tdG7jhEBrXPp
          Xcgmavb9yqVbAb2ASpBDFwnzcfve8dnr6TYLxQIDAQABAoH/AVt8hfvpGhHL0yS/
          L72Gv6v9ZIdqdEwaIKE6p2Ipx1753ZlFrSEXILBoKKYkjqI6ymEP09urHJe8knkG
          RMgji59327Hbi9SRrMdwJeOXFfyDfi1T0vokJxaq6EVAkZ6P4xjUWLpVP5PzMlNp
          O7HnmnTxTa7hHx50Rzwg+jB1/4itVpL03Cthf7xUH8Guij5wJY8rX6/U7GIj8dbk
          YLNIPFU6ak+qT2Pxw0lmCRdyOpAM5jZOszf9BqJkzVTJ4WqiA58AcN2K1CmoHHcn
          MnJ6IjRipwbVAuDWujUg33qyl6/HIZLcb6xk2ySfuHfBEwFM9JCrY/gLSErQVnT2
          TWMFAoGBAMafG3TeVj7MNLP4AkDzfoMbZJhHniw4DF1xlSB5q1Kl8THeD9hHc9Lv
          3JR4ApqTvbqLoBmwWxOGHtFVerUPwsiwEUDqslatg/SiCuLJ/iLuwXEqBp0nr23P
          ZWS5LsCU2Z3LTr45ouQUn0rdvOhtmcJ7ZzLjSr6avefSIbEgv01vAoGBAKac72np
          zUhRuMmcyBnll2zuWslOYhMeSRdgdAhk86eeINCCMamSpxgKsUyNNzP9mej0iAOr
          S8sP5vOZKpTWlqr/9s0fYMvGyf8Ii4KxS4Cdr9kNmbBEpvH7ZFRM6IobriYmHiNg
          n4sJ0KFY0kk725uW4C0JKn+uUhKBwIrJ8cgLAoGAKNzU/j87ySGj+h6dABXYQkrh
          cD7TuM8zJApZHtxJNfCz5YmFAv74Qj5cyCLEjl602usc3gwdQLAIKRMH8rYyYa1v
          b0aZuCFsk2i/Cpd59F/gZlK6F5zxh4rylj1O9Anrl34bTiF3dKsVdoaV9c+OoadX
          vO1sFDirt0TQ76sIEHsCgYBPbPzM1sIfuaWHpw/VGJgJO89Xq+AhEQzy8e4emlF1
          FHK8M3SNS/YQBfjjb2ZjiH+4h+nXJe+py9jjQ58C+RE2T3NN8alpO0jMJTysfuxp
          UcKkjFE5sGCNdrQrY8ZvICby1LUFVGh6FaG5aOhGNRzJnTEdBwOVfnptjCFHiGGU
          ZQKBgCSNLmfXSDavj04i4lRO2FGIsD+xghwBNI2TZmojnPDQ/S7f/XAoAHGtFSke
          X6fwkIspd79Ow4vepT0Dpgwn0tWdjlSTXXLZZDsYaUC3OPidpJmFhpg0Xhxs5ozZ
          XoBYSSnMnRX9gI1NB0ApbjL+SOLcCg5z45N64Bncw3AS2xAB
          -----END RSA PRIVATE KEY-----
  - type: web
    name: fill-sign-send-webhook
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/webhook_handler.py
    plan: free
    autoDeploy: false
    envVars:
      - key: WEBHOOK_PORT
        value: "8000"
